#!/usr/bin/env python3
"""Generate the deterministic, paste-friendly maximum-N ABC471E input."""

from __future__ import annotations

import argparse
import hashlib
import math
from collections import Counter
from pathlib import Path


N = 200_000
K = 100_000
MOD = 998_244_353
PERIOD = 997
LARGE_VALUES = (MOD - 1, MOD, MOD + 1, 1_000_000_000)
REQUIRED_VALUES = {1, 2, 3, *LARGE_VALUES}
DEFAULT_OUTPUT = Path(__file__).resolve().parent / "abc471e_code_test.in"


def value_at(index: int) -> int:
    """Return A[index], where index is zero-based."""
    if index % PERIOD == 0:
        return LARGE_VALUES[(index // PERIOD) % len(LARGE_VALUES)]
    return 1 + index % 3


def independent_answer(values: list[int]) -> int:
    """Count square and unordered-pair contributions with Python integers."""
    square_total = sum(value * value for value in values)

    pair_total = 0
    prefix = 0
    for value in values:
        pair_total += prefix * value
        prefix += value

    single_count = math.comb(N - 1, K - 1)
    pair_count = math.comb(N - 2, K - 2)
    answer = (single_count * square_total + 2 * pair_count * pair_total) % MOD

    # Algebraically equivalent cross-check, computed from the full integer sum.
    cross_check = (
        single_count * square_total
        + pair_count * (prefix * prefix - square_total)
    ) % MOD
    if answer != cross_check:
        raise AssertionError("independent answer cross-check failed")
    return answer


def generate(output: Path) -> None:
    values = [value_at(index) for index in range(N)]
    missing = REQUIRED_VALUES.difference(values)
    if missing:
        raise AssertionError(f"required values are missing: {sorted(missing)}")

    # Explicit ASCII encoding and LF make the resulting byte stream deterministic.
    content = f"{N} {K}\n{' '.join(map(str, values))}\n".encode("ascii")
    if len(content) >= 500_000:
        raise AssertionError(f"input is too large: {len(content)} bytes")

    output.write_bytes(content)
    actual = output.read_bytes()
    if actual != content:
        raise AssertionError("written file differs from generated bytes")

    counts = Counter(values)
    answer = independent_answer(values)
    digest = hashlib.sha256(actual).hexdigest()

    print(f"file={output.resolve()}")
    print(f"N={N}")
    print(f"K={K}")
    print(f"size={len(actual)}")
    print(f"sha256={digest}")
    print(f"answer={answer}")
    print(
        "required_counts="
        + ",".join(f"{value}:{counts[value]}" for value in sorted(REQUIRED_VALUES))
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("output", nargs="?", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    generate(args.output)


if __name__ == "__main__":
    main()
